#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III

bspc config border_width         5
bspc config border_radius        15
bspc config window_gap           15

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

picom -b
feh --bg-fill --randomize $HOME/wallpapers/*
bash ~/.config/polybar/launch.sh --shades

python3 -m http.server --bind localhost --directory "/home/ivan/.mozilla/firefox/StartPage/tilde-enhanced" 8000
